# Describes the execution time (in seconds) per actuator action
# CDR 2025
# These values are used to:
# - Simulate realistic delays when executing actuator actions in simulation
# - Plan action sequences with accurate timing estimates

time_per_action:
  THERMOMETER_LOWER_SERVO: 0.5
  THERMOMETER_RAISE_SERVO: 0.5
  TAKE_2_BOXES: 1.5
  BRING_2_BOXES_ON_TOP: 0.0 # not blocking
  PUT_2_LAST_BOXES_ON_THE_GROUND: 1.0
  PREPARE_TOP_PUSHER: 0.0 # not blocking
  GRAB_AND_SORT_2_BOXES_FROM_LIFT: 0.0 # not blocking
  PUSH_2_BOXES_OUT: 1.5
  OPEN_EXIT_RAMP: 0.0 # not blocking

  # System commands
  RESET_ACTUATORS: 3.0
  STOP_ALL_MOTORS: 0.0
  ENABLE_ALL_MOTORS: 0.0
  GET_READY: 0.0 # not blocking
