# Describes the execution time (in seconds) per actuator action
# CDR 2025
# These values are used to:
# - Simulate realistic delays when executing actuator actions in simulation
# - Plan action sequences with accurate timing estimates

time_per_action:
  THERMOMETER_LOWER_SERVO: 1.0
  THERMOMETER_RAISE_SERVO: 1.0
  LOWER_LEFT_ARM: 2.0
  LOWER_RIGHT_ARM: 2.0
  LET_GO_ELEMENTS_LEFT_ARM: 2.0
  LET_GO_ELEMENTS_RIGHT_ARM: 2.0
  STORE_PENDING_MASK: 0.0
  GET_READY_RIGHT_ARM: 2.0
  GET_READY_LEFT_ARM: 2.0 

  # System commands
  RESET_ACTUATORS: 3.0
  STOP_ALL_MOTORS: 0.0
  ENABLE_ALL_MOTORS: 0.0
  GET_READY: 0.0 # not blocking
