[mypy]
# mypy Configuration

# General options
check_untyped_defs = True
ignore_missing_imports = True

# Ignore specific errors (imports without stubs + ROS attributes)
disable_error_code = import-untyped, attr-defined

# Exclude launch files
exclude = (launch/.*\.py|setup\.py)

[mypy-champi_interfaces.*]
ignore_errors = True

[mypy-std_msgs.*]
ignore_errors = True

[mypy-nav_msgs.*]
ignore_errors = True

[mypy-geometry_msgs.*]
ignore_errors = True

[mypy-rclpy.*]
ignore_errors = True

[mypy-launch.*]
ignore_errors = True

[mypy-ament_index_python.*]
ignore_errors = True

[mypy-scipy.*]
ignore_errors = True

[mypy-yaml]
ignore_errors = True
