// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nanopb.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_nanopb_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_nanopb_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_nanopb_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_nanopb_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_nanopb_2eproto;
class NanoPBOptions;
class NanoPBOptionsDefaultTypeInternal;
extern NanoPBOptionsDefaultTypeInternal _NanoPBOptions_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::NanoPBOptions* Arena::CreateMaybeMessage<::NanoPBOptions>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum FieldType : int {
  FT_DEFAULT = 0,
  FT_CALLBACK = 1,
  FT_POINTER = 4,
  FT_STATIC = 2,
  FT_IGNORE = 3,
  FT_INLINE = 5
};
bool FieldType_IsValid(int value);
constexpr FieldType FieldType_MIN = FT_DEFAULT;
constexpr FieldType FieldType_MAX = FT_INLINE;
constexpr int FieldType_ARRAYSIZE = FieldType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FieldType_descriptor();
template<typename T>
inline const std::string& FieldType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, FieldType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function FieldType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    FieldType_descriptor(), enum_t_value);
}
inline bool FieldType_Parse(
    const std::string& name, FieldType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<FieldType>(
    FieldType_descriptor(), name, value);
}
enum IntSize : int {
  IS_DEFAULT = 0,
  IS_8 = 8,
  IS_16 = 16,
  IS_32 = 32,
  IS_64 = 64
};
bool IntSize_IsValid(int value);
constexpr IntSize IntSize_MIN = IS_DEFAULT;
constexpr IntSize IntSize_MAX = IS_64;
constexpr int IntSize_ARRAYSIZE = IntSize_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* IntSize_descriptor();
template<typename T>
inline const std::string& IntSize_Name(T enum_t_value) {
  static_assert(::std::is_same<T, IntSize>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function IntSize_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    IntSize_descriptor(), enum_t_value);
}
inline bool IntSize_Parse(
    const std::string& name, IntSize* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<IntSize>(
    IntSize_descriptor(), name, value);
}
enum TypenameMangling : int {
  M_NONE = 0,
  M_STRIP_PACKAGE = 1,
  M_FLATTEN = 2,
  M_PACKAGE_INITIALS = 3
};
bool TypenameMangling_IsValid(int value);
constexpr TypenameMangling TypenameMangling_MIN = M_NONE;
constexpr TypenameMangling TypenameMangling_MAX = M_PACKAGE_INITIALS;
constexpr int TypenameMangling_ARRAYSIZE = TypenameMangling_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TypenameMangling_descriptor();
template<typename T>
inline const std::string& TypenameMangling_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TypenameMangling>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TypenameMangling_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TypenameMangling_descriptor(), enum_t_value);
}
inline bool TypenameMangling_Parse(
    const std::string& name, TypenameMangling* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TypenameMangling>(
    TypenameMangling_descriptor(), name, value);
}
enum DescriptorSize : int {
  DS_AUTO = 0,
  DS_1 = 1,
  DS_2 = 2,
  DS_4 = 4,
  DS_8 = 8
};
bool DescriptorSize_IsValid(int value);
constexpr DescriptorSize DescriptorSize_MIN = DS_AUTO;
constexpr DescriptorSize DescriptorSize_MAX = DS_8;
constexpr int DescriptorSize_ARRAYSIZE = DescriptorSize_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DescriptorSize_descriptor();
template<typename T>
inline const std::string& DescriptorSize_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DescriptorSize>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DescriptorSize_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DescriptorSize_descriptor(), enum_t_value);
}
inline bool DescriptorSize_Parse(
    const std::string& name, DescriptorSize* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DescriptorSize>(
    DescriptorSize_descriptor(), name, value);
}
// ===================================================================

class NanoPBOptions PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NanoPBOptions) */ {
 public:
  inline NanoPBOptions() : NanoPBOptions(nullptr) {};
  virtual ~NanoPBOptions();

  NanoPBOptions(const NanoPBOptions& from);
  NanoPBOptions(NanoPBOptions&& from) noexcept
    : NanoPBOptions() {
    *this = ::std::move(from);
  }

  inline NanoPBOptions& operator=(const NanoPBOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline NanoPBOptions& operator=(NanoPBOptions&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NanoPBOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NanoPBOptions* internal_default_instance() {
    return reinterpret_cast<const NanoPBOptions*>(
               &_NanoPBOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NanoPBOptions& a, NanoPBOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(NanoPBOptions* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NanoPBOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NanoPBOptions* New() const final {
    return CreateMaybeMessage<NanoPBOptions>(nullptr);
  }

  NanoPBOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NanoPBOptions>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NanoPBOptions& from);
  void MergeFrom(const NanoPBOptions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NanoPBOptions* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NanoPBOptions";
  }
  protected:
  explicit NanoPBOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_nanopb_2eproto);
    return ::descriptor_table_nanopb_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIncludeFieldNumber = 24,
    kExcludeFieldNumber = 26,
    kCallbackDatatypeFieldNumber = 18,
    kCallbackFunctionFieldNumber = 19,
    kPackageFieldNumber = 25,
    kInitializerFieldNumber = 30,
    kMaxSizeFieldNumber = 1,
    kMaxCountFieldNumber = 2,
    kTypeFieldNumber = 3,
    kIntSizeFieldNumber = 7,
    kPackedStructFieldNumber = 5,
    kPackedEnumFieldNumber = 10,
    kSkipMessageFieldNumber = 6,
    kNoUnionsFieldNumber = 8,
    kMsgidFieldNumber = 9,
    kMaxLengthFieldNumber = 14,
    kAnonymousOneofFieldNumber = 11,
    kProto3FieldNumber = 12,
    kProto3SingularMsgsFieldNumber = 21,
    kEnumToStringFieldNumber = 13,
    kMangleNamesFieldNumber = 17,
    kFixedLengthFieldNumber = 15,
    kFixedCountFieldNumber = 16,
    kSubmsgCallbackFieldNumber = 22,
    kDefaultHasFieldNumber = 23,
    kDescriptorsizeFieldNumber = 20,
    kLongNamesFieldNumber = 4,
    kSortByTagFieldNumber = 28,
    kTypeOverrideFieldNumber = 27,
    kFallbackTypeFieldNumber = 29,
    kLabelOverrideFieldNumber = 31,
  };
  // repeated string include = 24;
  int include_size() const;
  private:
  int _internal_include_size() const;
  public:
  void clear_include();
  const std::string& include(int index) const;
  std::string* mutable_include(int index);
  void set_include(int index, const std::string& value);
  void set_include(int index, std::string&& value);
  void set_include(int index, const char* value);
  void set_include(int index, const char* value, size_t size);
  std::string* add_include();
  void add_include(const std::string& value);
  void add_include(std::string&& value);
  void add_include(const char* value);
  void add_include(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& include() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_include();
  private:
  const std::string& _internal_include(int index) const;
  std::string* _internal_add_include();
  public:

  // repeated string exclude = 26;
  int exclude_size() const;
  private:
  int _internal_exclude_size() const;
  public:
  void clear_exclude();
  const std::string& exclude(int index) const;
  std::string* mutable_exclude(int index);
  void set_exclude(int index, const std::string& value);
  void set_exclude(int index, std::string&& value);
  void set_exclude(int index, const char* value);
  void set_exclude(int index, const char* value, size_t size);
  std::string* add_exclude();
  void add_exclude(const std::string& value);
  void add_exclude(std::string&& value);
  void add_exclude(const char* value);
  void add_exclude(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& exclude() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_exclude();
  private:
  const std::string& _internal_exclude(int index) const;
  std::string* _internal_add_exclude();
  public:

  // optional string callback_datatype = 18 [default = "pb_callback_t"];
  bool has_callback_datatype() const;
  private:
  bool _internal_has_callback_datatype() const;
  public:
  void clear_callback_datatype();
  const std::string& callback_datatype() const;
  void set_callback_datatype(const std::string& value);
  void set_callback_datatype(std::string&& value);
  void set_callback_datatype(const char* value);
  void set_callback_datatype(const char* value, size_t size);
  std::string* mutable_callback_datatype();
  std::string* release_callback_datatype();
  void set_allocated_callback_datatype(std::string* callback_datatype);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_callback_datatype();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_callback_datatype(
      std::string* callback_datatype);
  private:
  const std::string& _internal_callback_datatype() const;
  void _internal_set_callback_datatype(const std::string& value);
  std::string* _internal_mutable_callback_datatype();
  public:

  // optional string callback_function = 19 [default = "pb_default_field_callback"];
  bool has_callback_function() const;
  private:
  bool _internal_has_callback_function() const;
  public:
  void clear_callback_function();
  const std::string& callback_function() const;
  void set_callback_function(const std::string& value);
  void set_callback_function(std::string&& value);
  void set_callback_function(const char* value);
  void set_callback_function(const char* value, size_t size);
  std::string* mutable_callback_function();
  std::string* release_callback_function();
  void set_allocated_callback_function(std::string* callback_function);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_callback_function();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_callback_function(
      std::string* callback_function);
  private:
  const std::string& _internal_callback_function() const;
  void _internal_set_callback_function(const std::string& value);
  std::string* _internal_mutable_callback_function();
  public:

  // optional string package = 25;
  bool has_package() const;
  private:
  bool _internal_has_package() const;
  public:
  void clear_package();
  const std::string& package() const;
  void set_package(const std::string& value);
  void set_package(std::string&& value);
  void set_package(const char* value);
  void set_package(const char* value, size_t size);
  std::string* mutable_package();
  std::string* release_package();
  void set_allocated_package(std::string* package);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_package();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_package(
      std::string* package);
  private:
  const std::string& _internal_package() const;
  void _internal_set_package(const std::string& value);
  std::string* _internal_mutable_package();
  public:

  // optional string initializer = 30;
  bool has_initializer() const;
  private:
  bool _internal_has_initializer() const;
  public:
  void clear_initializer();
  const std::string& initializer() const;
  void set_initializer(const std::string& value);
  void set_initializer(std::string&& value);
  void set_initializer(const char* value);
  void set_initializer(const char* value, size_t size);
  std::string* mutable_initializer();
  std::string* release_initializer();
  void set_allocated_initializer(std::string* initializer);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_initializer();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_initializer(
      std::string* initializer);
  private:
  const std::string& _internal_initializer() const;
  void _internal_set_initializer(const std::string& value);
  std::string* _internal_mutable_initializer();
  public:

  // optional int32 max_size = 1;
  bool has_max_size() const;
  private:
  bool _internal_has_max_size() const;
  public:
  void clear_max_size();
  ::PROTOBUF_NAMESPACE_ID::int32 max_size() const;
  void set_max_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_max_size() const;
  void _internal_set_max_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 max_count = 2;
  bool has_max_count() const;
  private:
  bool _internal_has_max_count() const;
  public:
  void clear_max_count();
  ::PROTOBUF_NAMESPACE_ID::int32 max_count() const;
  void set_max_count(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_max_count() const;
  void _internal_set_max_count(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional .FieldType type = 3 [default = FT_DEFAULT];
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  ::FieldType type() const;
  void set_type(::FieldType value);
  private:
  ::FieldType _internal_type() const;
  void _internal_set_type(::FieldType value);
  public:

  // optional .IntSize int_size = 7 [default = IS_DEFAULT];
  bool has_int_size() const;
  private:
  bool _internal_has_int_size() const;
  public:
  void clear_int_size();
  ::IntSize int_size() const;
  void set_int_size(::IntSize value);
  private:
  ::IntSize _internal_int_size() const;
  void _internal_set_int_size(::IntSize value);
  public:

  // optional bool packed_struct = 5 [default = false];
  bool has_packed_struct() const;
  private:
  bool _internal_has_packed_struct() const;
  public:
  void clear_packed_struct();
  bool packed_struct() const;
  void set_packed_struct(bool value);
  private:
  bool _internal_packed_struct() const;
  void _internal_set_packed_struct(bool value);
  public:

  // optional bool packed_enum = 10 [default = false];
  bool has_packed_enum() const;
  private:
  bool _internal_has_packed_enum() const;
  public:
  void clear_packed_enum();
  bool packed_enum() const;
  void set_packed_enum(bool value);
  private:
  bool _internal_packed_enum() const;
  void _internal_set_packed_enum(bool value);
  public:

  // optional bool skip_message = 6 [default = false];
  bool has_skip_message() const;
  private:
  bool _internal_has_skip_message() const;
  public:
  void clear_skip_message();
  bool skip_message() const;
  void set_skip_message(bool value);
  private:
  bool _internal_skip_message() const;
  void _internal_set_skip_message(bool value);
  public:

  // optional bool no_unions = 8 [default = false];
  bool has_no_unions() const;
  private:
  bool _internal_has_no_unions() const;
  public:
  void clear_no_unions();
  bool no_unions() const;
  void set_no_unions(bool value);
  private:
  bool _internal_no_unions() const;
  void _internal_set_no_unions(bool value);
  public:

  // optional uint32 msgid = 9;
  bool has_msgid() const;
  private:
  bool _internal_has_msgid() const;
  public:
  void clear_msgid();
  ::PROTOBUF_NAMESPACE_ID::uint32 msgid() const;
  void set_msgid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_msgid() const;
  void _internal_set_msgid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional int32 max_length = 14;
  bool has_max_length() const;
  private:
  bool _internal_has_max_length() const;
  public:
  void clear_max_length();
  ::PROTOBUF_NAMESPACE_ID::int32 max_length() const;
  void set_max_length(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_max_length() const;
  void _internal_set_max_length(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional bool anonymous_oneof = 11 [default = false];
  bool has_anonymous_oneof() const;
  private:
  bool _internal_has_anonymous_oneof() const;
  public:
  void clear_anonymous_oneof();
  bool anonymous_oneof() const;
  void set_anonymous_oneof(bool value);
  private:
  bool _internal_anonymous_oneof() const;
  void _internal_set_anonymous_oneof(bool value);
  public:

  // optional bool proto3 = 12 [default = false];
  bool has_proto3() const;
  private:
  bool _internal_has_proto3() const;
  public:
  void clear_proto3();
  bool proto3() const;
  void set_proto3(bool value);
  private:
  bool _internal_proto3() const;
  void _internal_set_proto3(bool value);
  public:

  // optional bool proto3_singular_msgs = 21 [default = false];
  bool has_proto3_singular_msgs() const;
  private:
  bool _internal_has_proto3_singular_msgs() const;
  public:
  void clear_proto3_singular_msgs();
  bool proto3_singular_msgs() const;
  void set_proto3_singular_msgs(bool value);
  private:
  bool _internal_proto3_singular_msgs() const;
  void _internal_set_proto3_singular_msgs(bool value);
  public:

  // optional bool enum_to_string = 13 [default = false];
  bool has_enum_to_string() const;
  private:
  bool _internal_has_enum_to_string() const;
  public:
  void clear_enum_to_string();
  bool enum_to_string() const;
  void set_enum_to_string(bool value);
  private:
  bool _internal_enum_to_string() const;
  void _internal_set_enum_to_string(bool value);
  public:

  // optional .TypenameMangling mangle_names = 17 [default = M_NONE];
  bool has_mangle_names() const;
  private:
  bool _internal_has_mangle_names() const;
  public:
  void clear_mangle_names();
  ::TypenameMangling mangle_names() const;
  void set_mangle_names(::TypenameMangling value);
  private:
  ::TypenameMangling _internal_mangle_names() const;
  void _internal_set_mangle_names(::TypenameMangling value);
  public:

  // optional bool fixed_length = 15 [default = false];
  bool has_fixed_length() const;
  private:
  bool _internal_has_fixed_length() const;
  public:
  void clear_fixed_length();
  bool fixed_length() const;
  void set_fixed_length(bool value);
  private:
  bool _internal_fixed_length() const;
  void _internal_set_fixed_length(bool value);
  public:

  // optional bool fixed_count = 16 [default = false];
  bool has_fixed_count() const;
  private:
  bool _internal_has_fixed_count() const;
  public:
  void clear_fixed_count();
  bool fixed_count() const;
  void set_fixed_count(bool value);
  private:
  bool _internal_fixed_count() const;
  void _internal_set_fixed_count(bool value);
  public:

  // optional bool submsg_callback = 22 [default = false];
  bool has_submsg_callback() const;
  private:
  bool _internal_has_submsg_callback() const;
  public:
  void clear_submsg_callback();
  bool submsg_callback() const;
  void set_submsg_callback(bool value);
  private:
  bool _internal_submsg_callback() const;
  void _internal_set_submsg_callback(bool value);
  public:

  // optional bool default_has = 23 [default = false];
  bool has_default_has() const;
  private:
  bool _internal_has_default_has() const;
  public:
  void clear_default_has();
  bool default_has() const;
  void set_default_has(bool value);
  private:
  bool _internal_default_has() const;
  void _internal_set_default_has(bool value);
  public:

  // optional .DescriptorSize descriptorsize = 20 [default = DS_AUTO];
  bool has_descriptorsize() const;
  private:
  bool _internal_has_descriptorsize() const;
  public:
  void clear_descriptorsize();
  ::DescriptorSize descriptorsize() const;
  void set_descriptorsize(::DescriptorSize value);
  private:
  ::DescriptorSize _internal_descriptorsize() const;
  void _internal_set_descriptorsize(::DescriptorSize value);
  public:

  // optional bool long_names = 4 [default = true];
  bool has_long_names() const;
  private:
  bool _internal_has_long_names() const;
  public:
  void clear_long_names();
  bool long_names() const;
  void set_long_names(bool value);
  private:
  bool _internal_long_names() const;
  void _internal_set_long_names(bool value);
  public:

  // optional bool sort_by_tag = 28 [default = true];
  bool has_sort_by_tag() const;
  private:
  bool _internal_has_sort_by_tag() const;
  public:
  void clear_sort_by_tag();
  bool sort_by_tag() const;
  void set_sort_by_tag(bool value);
  private:
  bool _internal_sort_by_tag() const;
  void _internal_set_sort_by_tag(bool value);
  public:

  // optional .google.protobuf.FieldDescriptorProto.Type type_override = 27;
  bool has_type_override() const;
  private:
  bool _internal_has_type_override() const;
  public:
  void clear_type_override();
  PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Type type_override() const;
  void set_type_override(PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Type value);
  private:
  PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Type _internal_type_override() const;
  void _internal_set_type_override(PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Type value);
  public:

  // optional .FieldType fallback_type = 29 [default = FT_CALLBACK];
  bool has_fallback_type() const;
  private:
  bool _internal_has_fallback_type() const;
  public:
  void clear_fallback_type();
  ::FieldType fallback_type() const;
  void set_fallback_type(::FieldType value);
  private:
  ::FieldType _internal_fallback_type() const;
  void _internal_set_fallback_type(::FieldType value);
  public:

  // optional .google.protobuf.FieldDescriptorProto.Label label_override = 31;
  bool has_label_override() const;
  private:
  bool _internal_has_label_override() const;
  public:
  void clear_label_override();
  PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Label label_override() const;
  void set_label_override(PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Label value);
  private:
  PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Label _internal_label_override() const;
  void _internal_set_label_override(PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Label value);
  public:

  // @@protoc_insertion_point(class_scope:NanoPBOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> include_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> exclude_;
  public:
  static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> _i_give_permission_to_break_this_code_default_callback_datatype_;
  private:
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr callback_datatype_;
  public:
  static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> _i_give_permission_to_break_this_code_default_callback_function_;
  private:
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr callback_function_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr package_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr initializer_;
  ::PROTOBUF_NAMESPACE_ID::int32 max_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 max_count_;
  int type_;
  int int_size_;
  bool packed_struct_;
  bool packed_enum_;
  bool skip_message_;
  bool no_unions_;
  ::PROTOBUF_NAMESPACE_ID::uint32 msgid_;
  ::PROTOBUF_NAMESPACE_ID::int32 max_length_;
  bool anonymous_oneof_;
  bool proto3_;
  bool proto3_singular_msgs_;
  bool enum_to_string_;
  int mangle_names_;
  bool fixed_length_;
  bool fixed_count_;
  bool submsg_callback_;
  bool default_has_;
  int descriptorsize_;
  bool long_names_;
  bool sort_by_tag_;
  int type_override_;
  int fallback_type_;
  int label_override_;
  friend struct ::TableStruct_nanopb_2eproto;
};
// ===================================================================

static const int kNanopbFileoptFieldNumber = 1010;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::NanoPBOptions >, 11, false >
  nanopb_fileopt;
static const int kNanopbMsgoptFieldNumber = 1010;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::NanoPBOptions >, 11, false >
  nanopb_msgopt;
static const int kNanopbEnumoptFieldNumber = 1010;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::NanoPBOptions >, 11, false >
  nanopb_enumopt;
static const int kNanopbFieldNumber = 1010;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::NanoPBOptions >, 11, false >
  nanopb;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NanoPBOptions

// optional int32 max_size = 1;
inline bool NanoPBOptions::_internal_has_max_size() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool NanoPBOptions::has_max_size() const {
  return _internal_has_max_size();
}
inline void NanoPBOptions::clear_max_size() {
  max_size_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NanoPBOptions::_internal_max_size() const {
  return max_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NanoPBOptions::max_size() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.max_size)
  return _internal_max_size();
}
inline void NanoPBOptions::_internal_set_max_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  max_size_ = value;
}
inline void NanoPBOptions::set_max_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_max_size(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.max_size)
}

// optional int32 max_length = 14;
inline bool NanoPBOptions::_internal_has_max_length() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_max_length() const {
  return _internal_has_max_length();
}
inline void NanoPBOptions::clear_max_length() {
  max_length_ = 0;
  _has_bits_[0] &= ~0x00002000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NanoPBOptions::_internal_max_length() const {
  return max_length_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NanoPBOptions::max_length() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.max_length)
  return _internal_max_length();
}
inline void NanoPBOptions::_internal_set_max_length(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00002000u;
  max_length_ = value;
}
inline void NanoPBOptions::set_max_length(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_max_length(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.max_length)
}

// optional int32 max_count = 2;
inline bool NanoPBOptions::_internal_has_max_count() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool NanoPBOptions::has_max_count() const {
  return _internal_has_max_count();
}
inline void NanoPBOptions::clear_max_count() {
  max_count_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NanoPBOptions::_internal_max_count() const {
  return max_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NanoPBOptions::max_count() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.max_count)
  return _internal_max_count();
}
inline void NanoPBOptions::_internal_set_max_count(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000020u;
  max_count_ = value;
}
inline void NanoPBOptions::set_max_count(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_max_count(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.max_count)
}

// optional .IntSize int_size = 7 [default = IS_DEFAULT];
inline bool NanoPBOptions::_internal_has_int_size() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool NanoPBOptions::has_int_size() const {
  return _internal_has_int_size();
}
inline void NanoPBOptions::clear_int_size() {
  int_size_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::IntSize NanoPBOptions::_internal_int_size() const {
  return static_cast< ::IntSize >(int_size_);
}
inline ::IntSize NanoPBOptions::int_size() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.int_size)
  return _internal_int_size();
}
inline void NanoPBOptions::_internal_set_int_size(::IntSize value) {
  assert(::IntSize_IsValid(value));
  _has_bits_[0] |= 0x00000080u;
  int_size_ = value;
}
inline void NanoPBOptions::set_int_size(::IntSize value) {
  _internal_set_int_size(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.int_size)
}

// optional .FieldType type = 3 [default = FT_DEFAULT];
inline bool NanoPBOptions::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool NanoPBOptions::has_type() const {
  return _internal_has_type();
}
inline void NanoPBOptions::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::FieldType NanoPBOptions::_internal_type() const {
  return static_cast< ::FieldType >(type_);
}
inline ::FieldType NanoPBOptions::type() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.type)
  return _internal_type();
}
inline void NanoPBOptions::_internal_set_type(::FieldType value) {
  assert(::FieldType_IsValid(value));
  _has_bits_[0] |= 0x00000040u;
  type_ = value;
}
inline void NanoPBOptions::set_type(::FieldType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.type)
}

// optional bool long_names = 4 [default = true];
inline bool NanoPBOptions::_internal_has_long_names() const {
  bool value = (_has_bits_[0] & 0x01000000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_long_names() const {
  return _internal_has_long_names();
}
inline void NanoPBOptions::clear_long_names() {
  long_names_ = true;
  _has_bits_[0] &= ~0x01000000u;
}
inline bool NanoPBOptions::_internal_long_names() const {
  return long_names_;
}
inline bool NanoPBOptions::long_names() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.long_names)
  return _internal_long_names();
}
inline void NanoPBOptions::_internal_set_long_names(bool value) {
  _has_bits_[0] |= 0x01000000u;
  long_names_ = value;
}
inline void NanoPBOptions::set_long_names(bool value) {
  _internal_set_long_names(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.long_names)
}

// optional bool packed_struct = 5 [default = false];
inline bool NanoPBOptions::_internal_has_packed_struct() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool NanoPBOptions::has_packed_struct() const {
  return _internal_has_packed_struct();
}
inline void NanoPBOptions::clear_packed_struct() {
  packed_struct_ = false;
  _has_bits_[0] &= ~0x00000100u;
}
inline bool NanoPBOptions::_internal_packed_struct() const {
  return packed_struct_;
}
inline bool NanoPBOptions::packed_struct() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.packed_struct)
  return _internal_packed_struct();
}
inline void NanoPBOptions::_internal_set_packed_struct(bool value) {
  _has_bits_[0] |= 0x00000100u;
  packed_struct_ = value;
}
inline void NanoPBOptions::set_packed_struct(bool value) {
  _internal_set_packed_struct(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.packed_struct)
}

// optional bool packed_enum = 10 [default = false];
inline bool NanoPBOptions::_internal_has_packed_enum() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool NanoPBOptions::has_packed_enum() const {
  return _internal_has_packed_enum();
}
inline void NanoPBOptions::clear_packed_enum() {
  packed_enum_ = false;
  _has_bits_[0] &= ~0x00000200u;
}
inline bool NanoPBOptions::_internal_packed_enum() const {
  return packed_enum_;
}
inline bool NanoPBOptions::packed_enum() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.packed_enum)
  return _internal_packed_enum();
}
inline void NanoPBOptions::_internal_set_packed_enum(bool value) {
  _has_bits_[0] |= 0x00000200u;
  packed_enum_ = value;
}
inline void NanoPBOptions::set_packed_enum(bool value) {
  _internal_set_packed_enum(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.packed_enum)
}

// optional bool skip_message = 6 [default = false];
inline bool NanoPBOptions::_internal_has_skip_message() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool NanoPBOptions::has_skip_message() const {
  return _internal_has_skip_message();
}
inline void NanoPBOptions::clear_skip_message() {
  skip_message_ = false;
  _has_bits_[0] &= ~0x00000400u;
}
inline bool NanoPBOptions::_internal_skip_message() const {
  return skip_message_;
}
inline bool NanoPBOptions::skip_message() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.skip_message)
  return _internal_skip_message();
}
inline void NanoPBOptions::_internal_set_skip_message(bool value) {
  _has_bits_[0] |= 0x00000400u;
  skip_message_ = value;
}
inline void NanoPBOptions::set_skip_message(bool value) {
  _internal_set_skip_message(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.skip_message)
}

// optional bool no_unions = 8 [default = false];
inline bool NanoPBOptions::_internal_has_no_unions() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool NanoPBOptions::has_no_unions() const {
  return _internal_has_no_unions();
}
inline void NanoPBOptions::clear_no_unions() {
  no_unions_ = false;
  _has_bits_[0] &= ~0x00000800u;
}
inline bool NanoPBOptions::_internal_no_unions() const {
  return no_unions_;
}
inline bool NanoPBOptions::no_unions() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.no_unions)
  return _internal_no_unions();
}
inline void NanoPBOptions::_internal_set_no_unions(bool value) {
  _has_bits_[0] |= 0x00000800u;
  no_unions_ = value;
}
inline void NanoPBOptions::set_no_unions(bool value) {
  _internal_set_no_unions(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.no_unions)
}

// optional uint32 msgid = 9;
inline bool NanoPBOptions::_internal_has_msgid() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_msgid() const {
  return _internal_has_msgid();
}
inline void NanoPBOptions::clear_msgid() {
  msgid_ = 0u;
  _has_bits_[0] &= ~0x00001000u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NanoPBOptions::_internal_msgid() const {
  return msgid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NanoPBOptions::msgid() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.msgid)
  return _internal_msgid();
}
inline void NanoPBOptions::_internal_set_msgid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00001000u;
  msgid_ = value;
}
inline void NanoPBOptions::set_msgid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_msgid(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.msgid)
}

// optional bool anonymous_oneof = 11 [default = false];
inline bool NanoPBOptions::_internal_has_anonymous_oneof() const {
  bool value = (_has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_anonymous_oneof() const {
  return _internal_has_anonymous_oneof();
}
inline void NanoPBOptions::clear_anonymous_oneof() {
  anonymous_oneof_ = false;
  _has_bits_[0] &= ~0x00004000u;
}
inline bool NanoPBOptions::_internal_anonymous_oneof() const {
  return anonymous_oneof_;
}
inline bool NanoPBOptions::anonymous_oneof() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.anonymous_oneof)
  return _internal_anonymous_oneof();
}
inline void NanoPBOptions::_internal_set_anonymous_oneof(bool value) {
  _has_bits_[0] |= 0x00004000u;
  anonymous_oneof_ = value;
}
inline void NanoPBOptions::set_anonymous_oneof(bool value) {
  _internal_set_anonymous_oneof(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.anonymous_oneof)
}

// optional bool proto3 = 12 [default = false];
inline bool NanoPBOptions::_internal_has_proto3() const {
  bool value = (_has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_proto3() const {
  return _internal_has_proto3();
}
inline void NanoPBOptions::clear_proto3() {
  proto3_ = false;
  _has_bits_[0] &= ~0x00008000u;
}
inline bool NanoPBOptions::_internal_proto3() const {
  return proto3_;
}
inline bool NanoPBOptions::proto3() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.proto3)
  return _internal_proto3();
}
inline void NanoPBOptions::_internal_set_proto3(bool value) {
  _has_bits_[0] |= 0x00008000u;
  proto3_ = value;
}
inline void NanoPBOptions::set_proto3(bool value) {
  _internal_set_proto3(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.proto3)
}

// optional bool proto3_singular_msgs = 21 [default = false];
inline bool NanoPBOptions::_internal_has_proto3_singular_msgs() const {
  bool value = (_has_bits_[0] & 0x00010000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_proto3_singular_msgs() const {
  return _internal_has_proto3_singular_msgs();
}
inline void NanoPBOptions::clear_proto3_singular_msgs() {
  proto3_singular_msgs_ = false;
  _has_bits_[0] &= ~0x00010000u;
}
inline bool NanoPBOptions::_internal_proto3_singular_msgs() const {
  return proto3_singular_msgs_;
}
inline bool NanoPBOptions::proto3_singular_msgs() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.proto3_singular_msgs)
  return _internal_proto3_singular_msgs();
}
inline void NanoPBOptions::_internal_set_proto3_singular_msgs(bool value) {
  _has_bits_[0] |= 0x00010000u;
  proto3_singular_msgs_ = value;
}
inline void NanoPBOptions::set_proto3_singular_msgs(bool value) {
  _internal_set_proto3_singular_msgs(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.proto3_singular_msgs)
}

// optional bool enum_to_string = 13 [default = false];
inline bool NanoPBOptions::_internal_has_enum_to_string() const {
  bool value = (_has_bits_[0] & 0x00020000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_enum_to_string() const {
  return _internal_has_enum_to_string();
}
inline void NanoPBOptions::clear_enum_to_string() {
  enum_to_string_ = false;
  _has_bits_[0] &= ~0x00020000u;
}
inline bool NanoPBOptions::_internal_enum_to_string() const {
  return enum_to_string_;
}
inline bool NanoPBOptions::enum_to_string() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.enum_to_string)
  return _internal_enum_to_string();
}
inline void NanoPBOptions::_internal_set_enum_to_string(bool value) {
  _has_bits_[0] |= 0x00020000u;
  enum_to_string_ = value;
}
inline void NanoPBOptions::set_enum_to_string(bool value) {
  _internal_set_enum_to_string(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.enum_to_string)
}

// optional bool fixed_length = 15 [default = false];
inline bool NanoPBOptions::_internal_has_fixed_length() const {
  bool value = (_has_bits_[0] & 0x00080000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_fixed_length() const {
  return _internal_has_fixed_length();
}
inline void NanoPBOptions::clear_fixed_length() {
  fixed_length_ = false;
  _has_bits_[0] &= ~0x00080000u;
}
inline bool NanoPBOptions::_internal_fixed_length() const {
  return fixed_length_;
}
inline bool NanoPBOptions::fixed_length() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.fixed_length)
  return _internal_fixed_length();
}
inline void NanoPBOptions::_internal_set_fixed_length(bool value) {
  _has_bits_[0] |= 0x00080000u;
  fixed_length_ = value;
}
inline void NanoPBOptions::set_fixed_length(bool value) {
  _internal_set_fixed_length(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.fixed_length)
}

// optional bool fixed_count = 16 [default = false];
inline bool NanoPBOptions::_internal_has_fixed_count() const {
  bool value = (_has_bits_[0] & 0x00100000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_fixed_count() const {
  return _internal_has_fixed_count();
}
inline void NanoPBOptions::clear_fixed_count() {
  fixed_count_ = false;
  _has_bits_[0] &= ~0x00100000u;
}
inline bool NanoPBOptions::_internal_fixed_count() const {
  return fixed_count_;
}
inline bool NanoPBOptions::fixed_count() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.fixed_count)
  return _internal_fixed_count();
}
inline void NanoPBOptions::_internal_set_fixed_count(bool value) {
  _has_bits_[0] |= 0x00100000u;
  fixed_count_ = value;
}
inline void NanoPBOptions::set_fixed_count(bool value) {
  _internal_set_fixed_count(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.fixed_count)
}

// optional bool submsg_callback = 22 [default = false];
inline bool NanoPBOptions::_internal_has_submsg_callback() const {
  bool value = (_has_bits_[0] & 0x00200000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_submsg_callback() const {
  return _internal_has_submsg_callback();
}
inline void NanoPBOptions::clear_submsg_callback() {
  submsg_callback_ = false;
  _has_bits_[0] &= ~0x00200000u;
}
inline bool NanoPBOptions::_internal_submsg_callback() const {
  return submsg_callback_;
}
inline bool NanoPBOptions::submsg_callback() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.submsg_callback)
  return _internal_submsg_callback();
}
inline void NanoPBOptions::_internal_set_submsg_callback(bool value) {
  _has_bits_[0] |= 0x00200000u;
  submsg_callback_ = value;
}
inline void NanoPBOptions::set_submsg_callback(bool value) {
  _internal_set_submsg_callback(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.submsg_callback)
}

// optional .TypenameMangling mangle_names = 17 [default = M_NONE];
inline bool NanoPBOptions::_internal_has_mangle_names() const {
  bool value = (_has_bits_[0] & 0x00040000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_mangle_names() const {
  return _internal_has_mangle_names();
}
inline void NanoPBOptions::clear_mangle_names() {
  mangle_names_ = 0;
  _has_bits_[0] &= ~0x00040000u;
}
inline ::TypenameMangling NanoPBOptions::_internal_mangle_names() const {
  return static_cast< ::TypenameMangling >(mangle_names_);
}
inline ::TypenameMangling NanoPBOptions::mangle_names() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.mangle_names)
  return _internal_mangle_names();
}
inline void NanoPBOptions::_internal_set_mangle_names(::TypenameMangling value) {
  assert(::TypenameMangling_IsValid(value));
  _has_bits_[0] |= 0x00040000u;
  mangle_names_ = value;
}
inline void NanoPBOptions::set_mangle_names(::TypenameMangling value) {
  _internal_set_mangle_names(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.mangle_names)
}

// optional string callback_datatype = 18 [default = "pb_callback_t"];
inline bool NanoPBOptions::_internal_has_callback_datatype() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool NanoPBOptions::has_callback_datatype() const {
  return _internal_has_callback_datatype();
}
inline void NanoPBOptions::clear_callback_datatype() {
  callback_datatype_.ClearToDefault(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_datatype_.get(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& NanoPBOptions::callback_datatype() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.callback_datatype)
  return _internal_callback_datatype();
}
inline void NanoPBOptions::set_callback_datatype(const std::string& value) {
  _internal_set_callback_datatype(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.callback_datatype)
}
inline std::string* NanoPBOptions::mutable_callback_datatype() {
  // @@protoc_insertion_point(field_mutable:NanoPBOptions.callback_datatype)
  return _internal_mutable_callback_datatype();
}
inline const std::string& NanoPBOptions::_internal_callback_datatype() const {
  return callback_datatype_.Get();
}
inline void NanoPBOptions::_internal_set_callback_datatype(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  callback_datatype_.Set(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_datatype_.get(), value, GetArena());
}
inline void NanoPBOptions::set_callback_datatype(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  callback_datatype_.Set(
    &::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_datatype_.get(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:NanoPBOptions.callback_datatype)
}
inline void NanoPBOptions::set_callback_datatype(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  callback_datatype_.Set(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_datatype_.get(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:NanoPBOptions.callback_datatype)
}
inline void NanoPBOptions::set_callback_datatype(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  callback_datatype_.Set(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_datatype_.get(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:NanoPBOptions.callback_datatype)
}
inline std::string* NanoPBOptions::_internal_mutable_callback_datatype() {
  _has_bits_[0] |= 0x00000001u;
  return callback_datatype_.Mutable(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_datatype_.get(), GetArena());
}
inline std::string* NanoPBOptions::release_callback_datatype() {
  // @@protoc_insertion_point(field_release:NanoPBOptions.callback_datatype)
  if (!_internal_has_callback_datatype()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return callback_datatype_.ReleaseNonDefault(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_datatype_.get(), GetArena());
}
inline void NanoPBOptions::set_allocated_callback_datatype(std::string* callback_datatype) {
  if (callback_datatype != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  callback_datatype_.SetAllocated(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_datatype_.get(), callback_datatype,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:NanoPBOptions.callback_datatype)
}
inline std::string* NanoPBOptions::unsafe_arena_release_callback_datatype() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NanoPBOptions.callback_datatype)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return callback_datatype_.UnsafeArenaRelease(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_datatype_.get(),
      GetArena());
}
inline void NanoPBOptions::unsafe_arena_set_allocated_callback_datatype(
    std::string* callback_datatype) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (callback_datatype != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  callback_datatype_.UnsafeArenaSetAllocated(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_datatype_.get(),
      callback_datatype, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NanoPBOptions.callback_datatype)
}

// optional string callback_function = 19 [default = "pb_default_field_callback"];
inline bool NanoPBOptions::_internal_has_callback_function() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool NanoPBOptions::has_callback_function() const {
  return _internal_has_callback_function();
}
inline void NanoPBOptions::clear_callback_function() {
  callback_function_.ClearToDefault(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_function_.get(), GetArena());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& NanoPBOptions::callback_function() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.callback_function)
  return _internal_callback_function();
}
inline void NanoPBOptions::set_callback_function(const std::string& value) {
  _internal_set_callback_function(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.callback_function)
}
inline std::string* NanoPBOptions::mutable_callback_function() {
  // @@protoc_insertion_point(field_mutable:NanoPBOptions.callback_function)
  return _internal_mutable_callback_function();
}
inline const std::string& NanoPBOptions::_internal_callback_function() const {
  return callback_function_.Get();
}
inline void NanoPBOptions::_internal_set_callback_function(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  callback_function_.Set(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_function_.get(), value, GetArena());
}
inline void NanoPBOptions::set_callback_function(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  callback_function_.Set(
    &::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_function_.get(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:NanoPBOptions.callback_function)
}
inline void NanoPBOptions::set_callback_function(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  callback_function_.Set(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_function_.get(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:NanoPBOptions.callback_function)
}
inline void NanoPBOptions::set_callback_function(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  callback_function_.Set(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_function_.get(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:NanoPBOptions.callback_function)
}
inline std::string* NanoPBOptions::_internal_mutable_callback_function() {
  _has_bits_[0] |= 0x00000002u;
  return callback_function_.Mutable(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_function_.get(), GetArena());
}
inline std::string* NanoPBOptions::release_callback_function() {
  // @@protoc_insertion_point(field_release:NanoPBOptions.callback_function)
  if (!_internal_has_callback_function()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return callback_function_.ReleaseNonDefault(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_function_.get(), GetArena());
}
inline void NanoPBOptions::set_allocated_callback_function(std::string* callback_function) {
  if (callback_function != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  callback_function_.SetAllocated(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_function_.get(), callback_function,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:NanoPBOptions.callback_function)
}
inline std::string* NanoPBOptions::unsafe_arena_release_callback_function() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NanoPBOptions.callback_function)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000002u;
  return callback_function_.UnsafeArenaRelease(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_function_.get(),
      GetArena());
}
inline void NanoPBOptions::unsafe_arena_set_allocated_callback_function(
    std::string* callback_function) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (callback_function != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  callback_function_.UnsafeArenaSetAllocated(&::NanoPBOptions::_i_give_permission_to_break_this_code_default_callback_function_.get(),
      callback_function, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NanoPBOptions.callback_function)
}

// optional .DescriptorSize descriptorsize = 20 [default = DS_AUTO];
inline bool NanoPBOptions::_internal_has_descriptorsize() const {
  bool value = (_has_bits_[0] & 0x00800000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_descriptorsize() const {
  return _internal_has_descriptorsize();
}
inline void NanoPBOptions::clear_descriptorsize() {
  descriptorsize_ = 0;
  _has_bits_[0] &= ~0x00800000u;
}
inline ::DescriptorSize NanoPBOptions::_internal_descriptorsize() const {
  return static_cast< ::DescriptorSize >(descriptorsize_);
}
inline ::DescriptorSize NanoPBOptions::descriptorsize() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.descriptorsize)
  return _internal_descriptorsize();
}
inline void NanoPBOptions::_internal_set_descriptorsize(::DescriptorSize value) {
  assert(::DescriptorSize_IsValid(value));
  _has_bits_[0] |= 0x00800000u;
  descriptorsize_ = value;
}
inline void NanoPBOptions::set_descriptorsize(::DescriptorSize value) {
  _internal_set_descriptorsize(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.descriptorsize)
}

// optional bool default_has = 23 [default = false];
inline bool NanoPBOptions::_internal_has_default_has() const {
  bool value = (_has_bits_[0] & 0x00400000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_default_has() const {
  return _internal_has_default_has();
}
inline void NanoPBOptions::clear_default_has() {
  default_has_ = false;
  _has_bits_[0] &= ~0x00400000u;
}
inline bool NanoPBOptions::_internal_default_has() const {
  return default_has_;
}
inline bool NanoPBOptions::default_has() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.default_has)
  return _internal_default_has();
}
inline void NanoPBOptions::_internal_set_default_has(bool value) {
  _has_bits_[0] |= 0x00400000u;
  default_has_ = value;
}
inline void NanoPBOptions::set_default_has(bool value) {
  _internal_set_default_has(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.default_has)
}

// repeated string include = 24;
inline int NanoPBOptions::_internal_include_size() const {
  return include_.size();
}
inline int NanoPBOptions::include_size() const {
  return _internal_include_size();
}
inline void NanoPBOptions::clear_include() {
  include_.Clear();
}
inline std::string* NanoPBOptions::add_include() {
  // @@protoc_insertion_point(field_add_mutable:NanoPBOptions.include)
  return _internal_add_include();
}
inline const std::string& NanoPBOptions::_internal_include(int index) const {
  return include_.Get(index);
}
inline const std::string& NanoPBOptions::include(int index) const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.include)
  return _internal_include(index);
}
inline std::string* NanoPBOptions::mutable_include(int index) {
  // @@protoc_insertion_point(field_mutable:NanoPBOptions.include)
  return include_.Mutable(index);
}
inline void NanoPBOptions::set_include(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:NanoPBOptions.include)
  include_.Mutable(index)->assign(value);
}
inline void NanoPBOptions::set_include(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:NanoPBOptions.include)
  include_.Mutable(index)->assign(std::move(value));
}
inline void NanoPBOptions::set_include(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  include_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:NanoPBOptions.include)
}
inline void NanoPBOptions::set_include(int index, const char* value, size_t size) {
  include_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:NanoPBOptions.include)
}
inline std::string* NanoPBOptions::_internal_add_include() {
  return include_.Add();
}
inline void NanoPBOptions::add_include(const std::string& value) {
  include_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:NanoPBOptions.include)
}
inline void NanoPBOptions::add_include(std::string&& value) {
  include_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:NanoPBOptions.include)
}
inline void NanoPBOptions::add_include(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  include_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:NanoPBOptions.include)
}
inline void NanoPBOptions::add_include(const char* value, size_t size) {
  include_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:NanoPBOptions.include)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
NanoPBOptions::include() const {
  // @@protoc_insertion_point(field_list:NanoPBOptions.include)
  return include_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
NanoPBOptions::mutable_include() {
  // @@protoc_insertion_point(field_mutable_list:NanoPBOptions.include)
  return &include_;
}

// repeated string exclude = 26;
inline int NanoPBOptions::_internal_exclude_size() const {
  return exclude_.size();
}
inline int NanoPBOptions::exclude_size() const {
  return _internal_exclude_size();
}
inline void NanoPBOptions::clear_exclude() {
  exclude_.Clear();
}
inline std::string* NanoPBOptions::add_exclude() {
  // @@protoc_insertion_point(field_add_mutable:NanoPBOptions.exclude)
  return _internal_add_exclude();
}
inline const std::string& NanoPBOptions::_internal_exclude(int index) const {
  return exclude_.Get(index);
}
inline const std::string& NanoPBOptions::exclude(int index) const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.exclude)
  return _internal_exclude(index);
}
inline std::string* NanoPBOptions::mutable_exclude(int index) {
  // @@protoc_insertion_point(field_mutable:NanoPBOptions.exclude)
  return exclude_.Mutable(index);
}
inline void NanoPBOptions::set_exclude(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:NanoPBOptions.exclude)
  exclude_.Mutable(index)->assign(value);
}
inline void NanoPBOptions::set_exclude(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:NanoPBOptions.exclude)
  exclude_.Mutable(index)->assign(std::move(value));
}
inline void NanoPBOptions::set_exclude(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  exclude_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:NanoPBOptions.exclude)
}
inline void NanoPBOptions::set_exclude(int index, const char* value, size_t size) {
  exclude_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:NanoPBOptions.exclude)
}
inline std::string* NanoPBOptions::_internal_add_exclude() {
  return exclude_.Add();
}
inline void NanoPBOptions::add_exclude(const std::string& value) {
  exclude_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:NanoPBOptions.exclude)
}
inline void NanoPBOptions::add_exclude(std::string&& value) {
  exclude_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:NanoPBOptions.exclude)
}
inline void NanoPBOptions::add_exclude(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  exclude_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:NanoPBOptions.exclude)
}
inline void NanoPBOptions::add_exclude(const char* value, size_t size) {
  exclude_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:NanoPBOptions.exclude)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
NanoPBOptions::exclude() const {
  // @@protoc_insertion_point(field_list:NanoPBOptions.exclude)
  return exclude_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
NanoPBOptions::mutable_exclude() {
  // @@protoc_insertion_point(field_mutable_list:NanoPBOptions.exclude)
  return &exclude_;
}

// optional string package = 25;
inline bool NanoPBOptions::_internal_has_package() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool NanoPBOptions::has_package() const {
  return _internal_has_package();
}
inline void NanoPBOptions::clear_package() {
  package_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& NanoPBOptions::package() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.package)
  return _internal_package();
}
inline void NanoPBOptions::set_package(const std::string& value) {
  _internal_set_package(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.package)
}
inline std::string* NanoPBOptions::mutable_package() {
  // @@protoc_insertion_point(field_mutable:NanoPBOptions.package)
  return _internal_mutable_package();
}
inline const std::string& NanoPBOptions::_internal_package() const {
  return package_.Get();
}
inline void NanoPBOptions::_internal_set_package(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  package_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NanoPBOptions::set_package(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  package_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:NanoPBOptions.package)
}
inline void NanoPBOptions::set_package(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  package_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:NanoPBOptions.package)
}
inline void NanoPBOptions::set_package(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000004u;
  package_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:NanoPBOptions.package)
}
inline std::string* NanoPBOptions::_internal_mutable_package() {
  _has_bits_[0] |= 0x00000004u;
  return package_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NanoPBOptions::release_package() {
  // @@protoc_insertion_point(field_release:NanoPBOptions.package)
  if (!_internal_has_package()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return package_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NanoPBOptions::set_allocated_package(std::string* package) {
  if (package != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  package_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), package,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:NanoPBOptions.package)
}
inline std::string* NanoPBOptions::unsafe_arena_release_package() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NanoPBOptions.package)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000004u;
  return package_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void NanoPBOptions::unsafe_arena_set_allocated_package(
    std::string* package) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (package != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  package_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      package, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NanoPBOptions.package)
}

// optional .google.protobuf.FieldDescriptorProto.Type type_override = 27;
inline bool NanoPBOptions::_internal_has_type_override() const {
  bool value = (_has_bits_[0] & 0x04000000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_type_override() const {
  return _internal_has_type_override();
}
inline void NanoPBOptions::clear_type_override() {
  type_override_ = 1;
  _has_bits_[0] &= ~0x04000000u;
}
inline PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Type NanoPBOptions::_internal_type_override() const {
  return static_cast< PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Type >(type_override_);
}
inline PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Type NanoPBOptions::type_override() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.type_override)
  return _internal_type_override();
}
inline void NanoPBOptions::_internal_set_type_override(PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Type value) {
  assert(PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Type_IsValid(value));
  _has_bits_[0] |= 0x04000000u;
  type_override_ = value;
}
inline void NanoPBOptions::set_type_override(PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Type value) {
  _internal_set_type_override(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.type_override)
}

// optional .google.protobuf.FieldDescriptorProto.Label label_override = 31;
inline bool NanoPBOptions::_internal_has_label_override() const {
  bool value = (_has_bits_[0] & 0x10000000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_label_override() const {
  return _internal_has_label_override();
}
inline void NanoPBOptions::clear_label_override() {
  label_override_ = 1;
  _has_bits_[0] &= ~0x10000000u;
}
inline PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Label NanoPBOptions::_internal_label_override() const {
  return static_cast< PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Label >(label_override_);
}
inline PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Label NanoPBOptions::label_override() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.label_override)
  return _internal_label_override();
}
inline void NanoPBOptions::_internal_set_label_override(PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Label value) {
  assert(PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Label_IsValid(value));
  _has_bits_[0] |= 0x10000000u;
  label_override_ = value;
}
inline void NanoPBOptions::set_label_override(PROTOBUF_NAMESPACE_ID::FieldDescriptorProto_Label value) {
  _internal_set_label_override(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.label_override)
}

// optional bool sort_by_tag = 28 [default = true];
inline bool NanoPBOptions::_internal_has_sort_by_tag() const {
  bool value = (_has_bits_[0] & 0x02000000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_sort_by_tag() const {
  return _internal_has_sort_by_tag();
}
inline void NanoPBOptions::clear_sort_by_tag() {
  sort_by_tag_ = true;
  _has_bits_[0] &= ~0x02000000u;
}
inline bool NanoPBOptions::_internal_sort_by_tag() const {
  return sort_by_tag_;
}
inline bool NanoPBOptions::sort_by_tag() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.sort_by_tag)
  return _internal_sort_by_tag();
}
inline void NanoPBOptions::_internal_set_sort_by_tag(bool value) {
  _has_bits_[0] |= 0x02000000u;
  sort_by_tag_ = value;
}
inline void NanoPBOptions::set_sort_by_tag(bool value) {
  _internal_set_sort_by_tag(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.sort_by_tag)
}

// optional .FieldType fallback_type = 29 [default = FT_CALLBACK];
inline bool NanoPBOptions::_internal_has_fallback_type() const {
  bool value = (_has_bits_[0] & 0x08000000u) != 0;
  return value;
}
inline bool NanoPBOptions::has_fallback_type() const {
  return _internal_has_fallback_type();
}
inline void NanoPBOptions::clear_fallback_type() {
  fallback_type_ = 1;
  _has_bits_[0] &= ~0x08000000u;
}
inline ::FieldType NanoPBOptions::_internal_fallback_type() const {
  return static_cast< ::FieldType >(fallback_type_);
}
inline ::FieldType NanoPBOptions::fallback_type() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.fallback_type)
  return _internal_fallback_type();
}
inline void NanoPBOptions::_internal_set_fallback_type(::FieldType value) {
  assert(::FieldType_IsValid(value));
  _has_bits_[0] |= 0x08000000u;
  fallback_type_ = value;
}
inline void NanoPBOptions::set_fallback_type(::FieldType value) {
  _internal_set_fallback_type(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.fallback_type)
}

// optional string initializer = 30;
inline bool NanoPBOptions::_internal_has_initializer() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool NanoPBOptions::has_initializer() const {
  return _internal_has_initializer();
}
inline void NanoPBOptions::clear_initializer() {
  initializer_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& NanoPBOptions::initializer() const {
  // @@protoc_insertion_point(field_get:NanoPBOptions.initializer)
  return _internal_initializer();
}
inline void NanoPBOptions::set_initializer(const std::string& value) {
  _internal_set_initializer(value);
  // @@protoc_insertion_point(field_set:NanoPBOptions.initializer)
}
inline std::string* NanoPBOptions::mutable_initializer() {
  // @@protoc_insertion_point(field_mutable:NanoPBOptions.initializer)
  return _internal_mutable_initializer();
}
inline const std::string& NanoPBOptions::_internal_initializer() const {
  return initializer_.Get();
}
inline void NanoPBOptions::_internal_set_initializer(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  initializer_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NanoPBOptions::set_initializer(std::string&& value) {
  _has_bits_[0] |= 0x00000008u;
  initializer_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:NanoPBOptions.initializer)
}
inline void NanoPBOptions::set_initializer(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000008u;
  initializer_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:NanoPBOptions.initializer)
}
inline void NanoPBOptions::set_initializer(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000008u;
  initializer_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:NanoPBOptions.initializer)
}
inline std::string* NanoPBOptions::_internal_mutable_initializer() {
  _has_bits_[0] |= 0x00000008u;
  return initializer_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NanoPBOptions::release_initializer() {
  // @@protoc_insertion_point(field_release:NanoPBOptions.initializer)
  if (!_internal_has_initializer()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return initializer_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NanoPBOptions::set_allocated_initializer(std::string* initializer) {
  if (initializer != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  initializer_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), initializer,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:NanoPBOptions.initializer)
}
inline std::string* NanoPBOptions::unsafe_arena_release_initializer() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NanoPBOptions.initializer)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000008u;
  return initializer_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void NanoPBOptions::unsafe_arena_set_allocated_initializer(
    std::string* initializer) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (initializer != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  initializer_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      initializer, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NanoPBOptions.initializer)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::FieldType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::FieldType>() {
  return ::FieldType_descriptor();
}
template <> struct is_proto_enum< ::IntSize> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::IntSize>() {
  return ::IntSize_descriptor();
}
template <> struct is_proto_enum< ::TypenameMangling> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::TypenameMangling>() {
  return ::TypenameMangling_descriptor();
}
template <> struct is_proto_enum< ::DescriptorSize> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DescriptorSize>() {
  return ::DescriptorSize_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_nanopb_2eproto
