# NEVER FORGET THE .0 when typing floats here

hardware_interface_simu:
  ros__parameters:
    enable_accel_limits: true

    max_acceleration_linear: 1.5 # m/s^2
    max_acceleration_angular: 10.1 # rad/s^2

    max_deceleration_linear: 10.0 # m/s^2
    max_deceleration_angular: 20.0 # rad/s^2
    
    max_acceleration_wheel: 100.0 # rad/s^2
    imu_vel_yaw_cov: 0.00001


hardware_interface:
  ros__parameters:

    device_ser_no: 3952366C3233

    covariances:
      pose_wheels: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001] # x y z roll pitch yaw
      vel_wheels: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      pose_otos: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      vel_otos: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    stm_config:
      cmd_vel_timeout: 1.0 # en seconde. Si aucune commande n'est reçue pendant ce temps, le robot s'arrête

      holo_drive_config:
        max_accel_wheel: 100.0 # rotation des roues en rotation/s²
        wheel_radius: 0.0292 # en m # 0.029
        base_radius: 0.13 # en m

        # order: wheel 0, wheel 1, wheel 2
        # TODO a copier dans HoloDrive.cpp puisque c'est pas pris en compte ??
        wheel_angles: [180.0, 120.0, 240.0] # angles of the wheels in degrees (CCW positive)
        wheel_distances: [0.13, 0.13, 0.13] # distance wheel to robot center in m

        max_acceleration_linear: 0.5 # m/s^2
        max_acceleration_angular: 6.0 # rad/s^2

        max_deceleration_linear: 10.0 # m/s^2
        max_deceleration_angular: 20.0 # rad/s^2

      otos_config: # You have to restart node AND STM to apply the otos config (feature, not bug :))
        linear_scalar: 1.02985 # [0.872 - 1.127]
        angular_scalar: 0.9899 # [0.872 - 1.127]

holo_teleop_joy_node:
  ros__parameters:
    max_linear_speed: 0.1 # m/s
    max_angular_speed: 1.0 # rad/s

twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      stop:
        topic   : /emergency/cmd_vel_stop
        timeout : 1.
        priority: 102
      joystick:
        topic   : /teleop/cmd_vel
        timeout : 0.5
        priority: 103
      behavior_server:
        topic   : /ctrl/cmd_vel
        timeout : 0.5
        priority: 101

ld_lidar:
  ros__parameters:
    product_name: 'LDLiDAR_LD19'
    topic_name: 'scan'
    frame_id: 'base_laser'
    port_name: '/dev/ttyUSB0'
    port_baudrate: 230400
    laser_scan_dir: true
    enable_angle_crop_func: false
    angle_crop_min: 135.0
    angle_crop_max: 225.0
    range_min: 0.05
    range_max: 5.0
    # units: 'M'

enemy_tracker:
  ros__parameters:
    crop_box:
      x_min: 0.1 # m
      x_max: 2.9 # m # TODO 2.9
      y_min: 0.1 # m
      y_max: 1.9 # m

costmap_updater:
  ros__parameters:
    grid_width: 3.0 # m # TODO NODE TO REMOVE
    grid_height: 2.0 # m
    grid_resolution: 0.05 # m/cell
    robot_radius: 0.22 # m
    enemy_robot_radius: 0.22 # m = 0.2 + margin
    enemy_pos_prediction_time: 0.0 # s. 0.0 means disabled

pose_controller:
  ros__parameters:
    control_loop_period: 0.02 # s
    max_linear_acceleration: 0.5 # m/s^2
    max_angular_acceleration: 6.0 # rad/s^2

    max_linear_deceleration: 4.0 # m/s^2 # TODO NOT USED --> on dirait que si non?
    max_angular_deceleration: 20.0 # rad/s^2 # TODO NOT USED
    # When the ctrl_goal is reached and end_speed!=0 (we expect a new goal to be sent right away),
    # the robot will emergency stop once the timeout is elapsed.
    timeout_wait_next_goal: 0.5 # s.

/**:
  ros__parameters:
    # Default motion parameters for strategy actions when not overridden in strategy files
    default_motion_speed: 0.5 # m/s
    default_motion_max_angular_speed: 3.0 # rad/s
    default_motion_end_speed: 0.0 # m/s # TODO a bit duplicated with pose_controller
    default_motion_accel_linear: 0.5 # m/s²
    default_motion_accel_angular: 6.0 # rad/s²
    default_motion_use_collision_avoidance: true
    default_motion_linear_tolerance: 0.005 # m = 5mm
    default_motion_angular_tolerance: 0.05 # rad = ~3 degrees


collision_detector:
  ros__parameters:
    vector_tolerance: 0.3
    time_threshold: 0.5

path_planner:
  ros__parameters:
    planner_loop_period: 0.05
    waypoint_tolerance: 0.03 # m. Waypoint tolerance should be higher because the robot doesn't stop at waypoints thus is less precise
    waypoint_speed_linear: 0.5 # m/s
    debug: true
    robot_radius: 0.28 # m = 0.22 (robot radius) + 0.04 (safety margin) # TODO 0.26
    enemy_robot_radius: 0.4 # m
    table_width: 3.0 # m (x dimension)
    table_height: 2.0 # m (y dimension)
    forbidden_area_wait_time: 1.0 # s. Time to wait when robot enters a forbidden area before exiting
    forbidden_area_margin: 0.05 # m. Margin before triggering forbidden area stop
    world_state_file: 'initial_world_state.yaml'  # World state file for zone obstacles

# Champi Brain nodes
/champi_brain/**:
  ros__parameters:
    initial_world_state_file: 'initial_world_state.yaml'  # Initial world state configuration file (shared by both nodes)

/champi_brain/state_machine_node:
  ros__parameters:
    # Strategy parameters
    use_default_strategy_and_color_in_sim: true       # If true, the default strategy file and color will be used in simulation mode without waiting for user to choose
    # use_default_strategy_and_color_in_sim: false       # If true, the default strategy file and color will be used in simulation mode without waiting for user to choose
#    default_strategy_file: '__strat_1_homologation_2026.py'
#    default_strategy_file: '__strat_2_test_square.py'
#    default_strategy_file: '__strat_3_test_square_with_rotations.py'
    default_strategy_file: '__strat_0_main_2026.py'     # Default strategy file for simulation
#    default_sim_color: 'BLUE'                       # Default team color for simulation: 'YELLOW' or 'BLUE'
    default_sim_color: 'YELLOW'                       # Default team color for simulation: 'YELLOW' or 'BLUE'

    # Match timing parameters
    match_total_time: 100.0                           # seconds - Total match duration
    return_home_safety_margin: 2.0                    # seconds - Safety margin for returning home --> means that the robot should be at home with this much time left
    simulate_actuators_delays: true                   # If false, actuators commands will be applied instantly (no delay simulation)

/champi_brain/world_state_node:
  ros__parameters:
    update_rate: 5.0 # Hz
    matching_distance_threshold: 0.1                  # meters. The maximum distance to consider that an observed object matches a known object
    max_missing: 10                                   # number of consecutive misses before an object is considered gone
