
base_controller_simu:
  ros__parameters:
    enable_accel_limits: true

    max_acceleration_linear: 0.5 # m/s^2
    max_deceleration_linear: 2.0 # m/s^2

    max_acceleration_angular: 4.0 # rad/s^2
    max_deceleration_angular: 20.0 # rad/s^2



base_controller:
  ros__parameters:

    topic_twist_in: "/cmd_vel"
    champi_can_verbose_mode: false
    timeout_connexion_ros: 1000000000000.0
    timeout_connexion_stm: 1.0

    start_x: 1.825 # m
    start_y: 0.175 # m
    start_theta: 1.57 # rad

    enable_accel_limits: true

    max_acceleration_linear: 0.5 # m/s^2
    max_deceleration_linear: 2.0 # m/s^2

    max_acceleration_angular: 4.0 # rad/s^2
    max_deceleration_angular: 20.0 # rad/s^2

    base_config:
      max_accel_wheels: 10.0 # rotation des roues en rotation/s²
      wheel_radius: 0.029 # en m
      base_radius: 0.175 # en m
      cmd_vel_timeout: 1.0 # en seconde. Si aucune commande n'est reçue pendant ce temps, le robot s'arrête
      # coin de la table



twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 10
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
      behavior_server:
        topic   : cmd_vel
        timeout : 0.5
        priority: 101