image_width: 640
image_height: 480
camera_name: mmal_service_16.1
camera_matrix:
  rows: 3
  cols: 3
  data: [628.757845,   0.     , 312.063610,
           0.     , 632.341450 , 248.408798,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob 
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.159577, -0.207655, 0.002495, -0.006916, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [648.600624,   0.     , 308.405628,   0.     ,
           0.     , 655.658295, 249.368195,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]

