image_width: 640
image_height: 480
camera_name: mmal_service_16.1
camera_matrix:
  rows: 3
  cols: 3
  data: [611.274916,   0.     , 317.944172,
           0.     , 676.932121 , 241.963753,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob 
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.002157, 0.001277, -0.000136, -0.001233, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [611.027488,   0.     , 317.287094,   0.     ,
           0.     , 677.359231, 241.905129,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]

