image_width: 1280
image_height: 800
camera_name: innomaker-ov9281
camera_matrix:
  rows: 3
  cols: 3
  data: [1061.6004 ,    0.     ,  677.33363,
            0.     , 1061.11181,  362.26716,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.455623, 0.192058, 0.001410, 0.001883, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [851.38811,   0.     , 700.68767,   0.     ,
           0.     , 984.60021, 357.1865 ,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
