[platformio]
default_envs = esp32dev-release

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = gin66/FastAccelStepper

[env:esp32dev-release]
build_flags =
	-DFIRMWARE_ENABLE_LOGS=0

[env:esp32dev-debug]
build_type = debug
build_flags =
	-DFIRMWARE_ENABLE_LOGS=1
